import type { CSSProperties } from "react";

function CashFlow() {
  const values = [52, 57, 45, 60, 68, 65, 62, 73, 68, 80, 85, 89];
  return <div className="pv-chart" role="img" aria-label="Illustrative monthly inflow and outflow for twelve months"><div className="pv-bars">{values.map((v,i) => <div key={i}><i style={{height:`${v}%`}}/><b style={{height:`${v*.78}%`}}/></div>)}</div><div className="pv-axis"><span>MAY</span><span>AUG</span><span>NOV</span><span>APR</span></div></div>;
}
export function LendingPreview({ tool = "CAM generation" }: { tool?: string }) {
  return <div className="product-preview pv-lending">
    <div className="pv-top"><span>NEWRON / CREDIT WORKSPACE</span><i>ILLUSTRATIVE</i></div>
    <div className="pv-heading"><div><small>APPLICATION / LP-2884109</small><h4>{tool}</h4></div><span className="pv-status">Officer review</span></div>
    {tool === "Statement analyser" ? <><div className="pv-metrics"><div><small>Total inflow</small><strong>₹ 47.4L</strong></div><div><small>Avg. balance</small><strong>₹ 1.84L</strong></div><div><small>Bounce events</small><strong>0</strong></div></div><CashFlow/><div className="pv-note">Salary regularity: 11 / 12 months. December delay flagged.</div></> : tool === "Applicant 360°" ? <><div className="pv-party"><span>RI</span><div><strong>R. Iyer</strong><small>Applicant · Iyer Traders</small></div></div><div className="pv-metrics"><div><small>Identity</small><strong>Matched</strong></div><div><small>Income</small><strong>Mapped</strong></div><div><small>Collateral</small><strong>Linked</strong></div></div><div className="pv-note">Bank statement + ITR + GST → one borrower view.</div></> : tool === "Video PD" ? <><div className="pv-video"><div className="pv-person">RI</div><span>PERSONAL DISCUSSION / SAMPLE</span><div className="pv-face-corner" /></div><div className="pv-checks"><span>✓ Identity check</span><span>✓ Address check</span><span>↗ Report → CAM</span></div></> : tool === "Policy chat" ? <><div className="pv-question">What happens when DTI exceeds 0.45?</div><div className="pv-answer">Flag the deviation for review against the permitted tier override.</div><div className="pv-source">SOURCE / CREDIT POLICY · DTI CLAUSE</div></> : tool === "Deviation engine" ? <><div className="pv-risk"><span>!</span><div><small>POLICY DEVIATION</small><h4>DTI above 0.45</h4></div></div><div className="pv-review-steps"><span>Detected</span><b>→</b><span>Classified</span><b>→</b><span>Tier-2 review</span></div><div className="pv-note">Reason code attached. Maker-checker required.</div></> : <><div className="pv-memo"><span>06 / COLLATERAL ASSESSMENT</span><p>Proposed loan <mark>₹ 38,00,000</mark> secured against residential property.</p><div className="pv-citation">↳ Valuation report · source attached</div><div className="pv-memo-lines"><i/><i/><i/></div></div><div className="pv-flag"><span>!</span> DTI deviation flagged <b>Tier-2 review ↗</b></div><div className="pv-checks"><span>✓ Your format</span><span>✓ Policy citations</span><span>✓ Audit trail</span></div></>}
  </div>;
}
export function ClaimsPreview({ compact = false }: { compact?: boolean }) {
  return <div className={`product-preview pv-claims ${compact ? "pv-compact" : ""}`}><div className="pv-top"><span>NEWRON / CLAIMS</span><i>ILLUSTRATIVE</i></div><div className="pv-heading"><div><small>CL-2026-9881</small><h4>Cardiac · Inpatient</h4></div><strong className="pv-amount">₹ 4.2L</strong></div><div className="pv-claim-gauge"><svg viewBox="0 0 180 110" aria-hidden="true"><path d="M20 90a70 70 0 0 1 140 0" fill="none" stroke="#ffffff12" strokeWidth="9"/><path d="M20 90a70 70 0 0 1 138-15" fill="none" stroke="#91cdbb" strokeWidth="9" strokeLinecap="round"/></svg><div><strong>11 / 11</strong><small>Documents complete</small></div></div><div className="pv-claim-checks"><span>Policy eligibility <b>Checked</b></span><span>Denial risk <b>Reviewable</b></span><span>TPA packet <b>Assembled</b></span></div><div className="pv-note">Evidence attached for the claims team’s review.</div></div>;
}
export function CitizenPreview() {
  return <div className="product-preview pv-citizen"><div className="pv-top"><span>NEWRON / CITIZEN SERVICES</span><i>ILLUSTRATIVE</i></div><div className="pv-voice"><span className="pv-mic">◉</span><div className="pv-wave" aria-hidden="true">{Array.from({length:23},(_,i)=><i key={i} style={{"--h":12+Math.abs(Math.sin(i*1.3))*35} as CSSProperties}/>)}</div><small>VOICE INTAKE / KANNADA</small></div><div className="pv-citizen-message"><span lang="kn">ನಮಸ್ಕಾರ</span><small>A citizen speaks. The service listens.</small></div><div className="pv-citizen-route"><span>Transcribe</span><b>→</b><span>Find policy</span><b>→</b><span>Draft reply</span></div><div className="pv-human"><i/>Officer approval before a response is sent</div></div>;
}
export function DeploymentPreview() {
  return <div className="product-preview pv-deploy"><div className="pv-top"><span>YOUR ENVIRONMENT</span><i>PRIVATE BY DESIGN</i></div><div className="pv-boundary"><span>DATA PERIMETER</span><div className="pv-server"><i/><i/><i/><b>ArthaLM</b></div><div className="pv-deploy-nodes"><span>Documents</span><span>Tools</span><span>Applications</span></div></div><div className="pv-human"><i/>Your keys. Your audit trail.</div></div>;
}
